# Generated by Django 4.1.4 on 2023-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=20)),
                ('medical_history', models.TextField()),
                ('safety_breaches', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
